{% set name = "lobsterpy" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lobsterpy-{{ version }}.tar.gz
  sha256: 6fbfbbceb71e65b33be9b383c8928d5742ed856f2a4da85f4704cdb25946073b
  patches:
    - setup.patch

build:
  entry_points:
    - lobsterpy = lobsterpy.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <3.12,>=3.9
    - setuptools >=65.0.0
    - wheel
    - pip
  run:
    - python <3.12,>=3.9
    - pymatgen >=2024.4.13
    - numpy
    - typing

test:
  imports:
    - lobsterpy
  commands:
    - pip check
    - lobsterpy --help
  requires:
    - pip

about:
  home: https://github.com/jageo/lobsterpy
  summary: Package for automatic bonding analysis with Lobster/VASP
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
