{% set name = "lobsterpy" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lobsterpy-{{ version }}.tar.gz
  sha256: 031bd3de290f2b9903930246427f6c50085ab55dc44b4608ee4053bb3fc4d519
  patches:
    - setup.patch

build:
  entry_points:
    - lobsterpy = lobsterpy.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <3.12,>=3.9
    - setuptools >=65.0.0
    - wheel
    - pip
  run:
    - python <3.12,>=3.9
    - pymatgen >=2024.9.10
    - numpy <3.0.0
    - typing

test:
  imports:
    - lobsterpy
  commands:
    - pip check
    - lobsterpy --help
  requires:
    - pip

about:
  home: https://github.com/jageo/lobsterpy
  summary: Package for automatic bonding analysis with Lobster/VASP
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JaGeo
    - naik-aakash
    - jan-janssen
