{% set name = "lobsterpy" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lobsterpy-{{ version }}.tar.gz
  sha256: bb510ef7286398283266b1094114817154a09a4bd31ca9f77b39b1e47e5917ca
  patches:
    - setup.patch

build:
  entry_points:
    - lobsterpy = lobsterpy.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pymatgen >=2023.9.10
    - numpy
    - typing

test:
  imports:
    - lobsterpy
  commands:
    - pip check
    - lobsterpy --help
  requires:
    - pip

about:
  home: https://github.com/jageo/lobsterpy
  summary: Package for autmatic bonding analysis with Lobster/VASP
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
