{% set name = "lobsterpy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lobsterpy-{{ version }}.tar.gz
  sha256: 5d307d802709fd15127b258c3e4a43e94fb56a476f6cae0a3e68f254234c73d3

build:
  entry_points:
    - lobsterpy = lobsterpy.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pymatgen >=2023.1.20
    - numpy
    - typing
    - sphinx >=4
    - sphinx-argparse ==0.4.0
    - sphinx-pdj-theme ==0.2.1

test:
  imports:
    - lobsterpy
  commands:
    - pip check
    - lobsterpy --help
  requires:
    - pip

about:
  home: https://github.com/jageo/lobsterpy
  summary: Package for autmatic bonding analysis with Lobster/VASP
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
