{% set name = "lobsterpy" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lobsterpy-{{ version }}.tar.gz
  sha256: 6852e15eb63c77fce70ffe6dcca50a07316b092c08696a2c806c6846b7b627e8
  patches:
    - setup.patch

build:
  entry_points:
    - lobsterpy = lobsterpy.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <3.12,>=3.9
    - setuptools >=65.0.0
    - wheel
    - pip
  run:
    - python <3.12,>=3.9
    - pymatgen >=2024.2.23
    - numpy
    - typing

test:
  imports:
    - lobsterpy
  commands:
    - pip check
    - lobsterpy --help
  requires:
    - pip

about:
  home: https://github.com/jageo/lobsterpy
  summary: Package for automatic bonding analysis with Lobster/VASP
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
